### ISSUE TITLE
New Population Importer (e.g. RIL, NAM)

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/uofspb_germplasm#14]
The functionality described in #13 requires the germplasm already to exist.

## Original Needs Description

We have a number of RIL populations that need to be entered into KnowPulse. We currently save these as shown below. This importer should be able to select the existing RIL population stock and then using a list of RIL individuals provided via a file, the importer should create entries in the stock table for each RIL individual and add the needed relationships to connect it to the population.
![Work Notes-61](https://user-images.githubusercontent.com/1566301/201192013-1bdc8cbc-3053-4a67-9659-cfbfbf4a8cae.jpg)

## Additional considerations

 - We may want to code this as a generic individual of population importer for more use cases. This could be done by allowing any stock record to be selected as the "population" and the ability to select the relationship type to use.
 - Since we are creating the population (i.e. RIL) individuals, we will need to know their organism, type, name and uniquename. 
 - We typically create our uniquename using a pattern so we will want to support that similar to the other importers Yichao made. 
 - For max flexibility we may want to have the organism and type in the file as well so it doesn't have to be the same throughout the population.
 - We may also want to allow the uniquename to be included in the file or calculated via pattern if not provided.

### Form

- Population Stock*: autocomplete pulling from all stock records
- Relationship Type*: autocomplete pulling from all cvterms, is_individual_of_population is the default
- Population Stock Position in Relationship*: Radios with subject + object, description includes an example, default is object
- Uniquename Pattern: See Yichao's importers and use same mechanism. I think it's a prefix approach.
- File Upload: provided by Tripal importer

### File

- Name: the name of the RIL individual
- Type: the name of the cvterm which should be used for the stock record, must exist
- Scientific Name: the genus + species of the organism to be used for the stock record, must exist
- Uniquename (optional): the uniquename to use if you do not want to use the pattern.

**Comment by reynoldtan** [comment]
Mockup 1 of proposed interface

![RIL importer](https://user-images.githubusercontent.com/15472253/213807132-b09cf330-94d4-4595-b6d4-2f0e24b23035.jpg)

**Comment by laceysanderson** [comment]
Note: work on this importer was started already in this branch: `14-new-population-importer` although not much progress was made, the importer file is created, configured and the form is started.

A couple of notes about your proposed interface above:

- There should be an option to select whether the grouping "population" stock is the object or subject of the relationship. This should be added to the relationship fieldset.
- Change the "(Object) Stock" fieldset to be "Population Entry (e.g. RIL-123)"
- The relationship form element should be called "Relationship Verb" with text describing that this is the type of relationship linking the population entry with all members of the population.
- Change the "(Subject) Stock" fieldset to "Population Individuals" with text describing that each row in the file should describe a specific individual to be created and linked to the Population entry with the specified relationship.
- I like the graphic! You'll just need to change the subject/object naming to population entry and individual

**Comment by reynoldtan** [comment]
Revised mockup - Mockup 2

Updated the illustration to show 2 ways population can be loaded and corresponds to the options (radio buttons) in Relationship Verb fieldset.

A Note/description added to Population Individuals fieldset relating to expected columns.

![ril importer 02](https://user-images.githubusercontent.com/15472253/214613456-566c40d8-d85a-4261-80a5-cee49905545a.jpg)

**Comment by reynoldtan** [comment]
Revised mockup - Mockup 3

The collapsible section containing the illustration is now part of the relationship verb fieldset where it is the most relevant.

![ril importer 03](https://user-images.githubusercontent.com/15472253/214642121-43133f85-38a4-4697-9b87-ab00882a887f.jpg)

**Comment by reynoldtan** [comment]
Revisions to final mockup
![ril importer 03](https://user-images.githubusercontent.com/15472253/214892550-c4082200-392d-4c01-8056-e84df30292c6.jpg)

**Comment by laceysanderson** [comment]
Yes, these changes look good :-)
