### ISSUE TITLE
Exclude any characters

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/uofspb_germplasm#21]
1. Exclude any characters when generating uniquenames - : (colon characters) is added between characters prefix and unique number so that when prefix is GERM:LINE, the resulting value would be GERM:LINE:29349.

Let user account for any special characters to add to the prefix.

2. Supply a value to dbxref_id when inserting a stock record.

**Comment by laceysanderson** [comment]
> Supply a value to dbxref_id when inserting a stock record.

For the dbxref, the admin can configure a single database to be used for all imports. Then the dbxref.accession = stock.uniquename which is generated based on the prefix.
